import { ColDef } from '@ag-grid-community/core';
import { formatNumber } from '../../../utils/formatting';

export const positionColumnDefs: ColDef[] = [
  { field: 'INSTRUMENT_NAME', headerName: 'Instrument', sort: 'desc' },
  {
    field: 'BUY_QUANTITY',
    headerName: 'Buy Quantity',
    valueFormatter: formatNumber(0),
    type: 'rightAligned',
    flex: 1,
    enableCellChangeFlash: true,
  },
  {
    field: 'BUY_AVG_PX',
    headerName: 'Buy Avg Px',
    valueFormatter: formatNumber(2),
    type: 'rightAligned',
    flex: 1,
    enableCellChangeFlash: true,
  },
  {
    field: 'SELL_QUANTITY',
    headerName: 'Sell Quantity',
    valueFormatter: formatNumber(0),
    type: 'rightAligned',
    flex: 1,
    enableCellChangeFlash: true,
  },
  {
    field: 'SELL_AVG_PX',
    headerName: 'Sell Avg Px',
    valueFormatter: formatNumber(2),
    type: 'rightAligned',
    flex: 1,
    enableCellChangeFlash: true,
  },
  {
    field: 'NET_QUANTITY',
    headerName: 'Quantity',
    valueFormatter: formatNumber(0),
    type: 'rightAligned',
    flex: 1,
    enableCellChangeFlash: true,
  },
  {
    field: 'NET_AVG_PX',
    headerName: 'Net Avg Px',
    valueFormatter: formatNumber(2),
    type: 'rightAligned',
    flex: 1,
    enableCellChangeFlash: true,
  },
  {
    field: 'OPENING_VALUE',
    headerName: 'Opening Value',
    valueFormatter: formatNumber(2),
    type: 'rightAligned',
    flex: 1,
    enableCellChangeFlash: true,
  },
  {
    field: 'REFINITIV_LAST_PX',
    headerName: 'Refinitiv Last Px',
    valueFormatter: formatNumber(2),
    type: 'rightAligned',
    flex: 1,
    enableCellChangeFlash: true,
  },
  {
    field: 'CURRENT_VALUE',
    headerName: 'Current Value',
    valueFormatter: formatNumber(2),
    type: 'rightAligned',
    flex: 1,
    enableCellChangeFlash: true,
  },
  {
    field: 'PNL',
    headerName: 'PNL',
    valueFormatter: formatNumber(2),
    type: 'rightAligned',
    flex: 1,
    enableCellChangeFlash: true,
  },
];
